---
- name: Install and configure Ollama on AI agents
  hosts: all
  become: true
  roles:
    - system_timezone
    - essential-packages
    - nvm
    - ollama
  post_tasks:
    - name: Reboot machine to apply kernel updates
      ansible.builtin.reboot:
        msg: "Rebooting machine to apply any pending kernel updates"

    - name: VM Ready for OpenClaw !
      ansible.builtin.debug:
        msg: |
          "{{ inventory_hostname }} is ready to install OpenClaw, unfortunately this cannot be automated with Ollama yet."
          "Please continue with the OpenClaw installation manually."
          "Connect to the VM with 'ssh {{ ansible_user }}@{{ ansible_host }}'"
          "Then run 'ollama launch openclaw' to start the installation."
