---
- name: Install and configure Ollama on AI agents
  hosts: all
  become: true
  roles:
    - system_timezone
    - essential-packages
    - nvm
    - ollama

# - name: Install and configure OpenClaw
#   hosts: openclaw
#   become: true
#   roles:
#     - openclaw
