---
- name: Install and configure Ollama on AI agents
  hosts: all
  become: true
  roles:
    - system_timezone
    - essential-packages
    - nvm
    - ollama

  post_tasks:
    - name: Reboot machine to apply kernel updates
      ansible.builtin.reboot:
        msg: "Rebooting machine to apply any pending kernel updates"
# - name: Install and configure OpenClaw
#   hosts: openclaw
#   become: true
#   roles:
#     - openclaw
